### PR TITLE
recognize core booleans in is_bool()

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by haarg** [comment]
A concern here is that depending on the version of Cpanel::JSON::XS, is_bool may return true for a value that does not get encoded as a boolean.

**Comment by karenetheridge** [comment]
Yes. I noted that in the Changes entry. Force-requiring the latest version is probably too much though? Maybe not if combined with a perl version check.

**Comment by karenetheridge** [comment]
I bumped the minimum Cpanel::JSON::XS version on perls that have `builtin`, to ensure serialization works correctly.

**Comment by gurnec** [comment]
Hi! Just thought you should know that these two tests are failing for Perl 5.34:

https://github.com/p5sagit/JSON-MaybeXS/pull/3/commits/d71ee63639c25d69ef01831f00f77fc49903e55f#diff-3d48725130685ec3a9f564d8ee75b7a15d869fc2751d652803a593804b73e806R39-R40

I presume they should be moved up to the prior SKIP block.

**Comment by karenetheridge** [comment]
Thanks, investigating.

I made a release just now but I hit ENTER in haste and I think I can do better... will follow up with another shortly.

**Pull request merged**
